global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'system'
    static_configs:
      - targets: [ 'host.docker.internal:9101' ]

  - job_name: 'api_gateway_microservice'
    static_configs:
      - targets: [ 'api_gateway:8001' ]

  - job_name: 'writer_microservice'
    static_configs:
      - targets: [ 'writer_service:8002' ]

  - job_name: 'reader_microservice'
    static_configs:
      - targets: [ 'reader_service:8003' ]
