serviceName: reader_service
grpc:
  port: :5003
  development: true
probes:
  readinessPath: /ready
  livenessPath: /live
  port: :3003
  pprof: :6003
  prometheusPath: /metrics
  prometheusPort: :8003
  checkIntervalSeconds: 10
logger:
  level: debug
  devMode: false
  encoder: json
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbName: products
  sslMode: false
kafka:
  brokers: [ "localhost:9092" ]
  groupID: writer_microservice_consumer
  initTopics: true
kafkaTopics:
  productCreate:
    topicName: product_create
    partitions: 10
    replicationFactor: 1
  productUpdate:
    topicName: product_update
    partitions: 10
    replicationFactor: 1
  productCreated:
    topicName: product_created
    partitions: 10
    replicationFactor: 1
  productUpdated:
    topicName: product_updated
    partitions: 10
    replicationFactor: 1
redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  poolSize: 300
mongo:
  uri: "mongodb://localhost:27017"
  user: admin
  password: admin
  db: products
mongoCollections:
  products: products
serviceSettings:
  redisProductPrefixKey: "reader:product"
jaeger:
  enable: true
  serviceName: reader_service
  hostPort: "localhost:6831"